spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dndy?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        #url: jdbc:mysql://223.247.212.56:3306/saxd?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: root
        password: root
        #password: SAxd13578@#Master
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    aop:
      proxy-target-class: true
    http:
      multipart:
        maxFileSize: 1024MB
        maxRequestSize: 1024MB

mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.dndy.model
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8989

logging:
  config: classpath:log4j2.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



